Repository Sesac-team-03/TreasureHunt, pull requests merged in 2024-03, with the labels that each got.

#109 refactor: User -> NaverUser 클래스명 변경 및 패키지 이동
  app/src/main/java/com/treasurehunt/ui/login/LogInFragment.kt
  app/src/main/java/com/treasurehunt/ui/login/LoginViewModel.kt
  app/src/main/java/com/treasurehunt/ui/model/NaverUser.kt
Labels: refactoring

#133 프로필 화면 비즈니스 로직 뷰모델로 이전 및 기타 리팩토링
  app/build.gradle.kts
  app/src/main/java/com/treasurehunt/ui/home/HomeActivity.kt
  app/src/main/java/com/treasurehunt/ui/login/LogInFragment.kt
  app/src/main/java/com/treasurehunt/ui/login/LoginViewModel.kt
  app/src/main/java/com/treasurehunt/ui/login/PreloadFragment.kt
  app/src/main/java/com/treasurehunt/ui/login/SplashFragment.kt
  app/src/main/java/com/treasurehunt/ui/model/ProfileUiState.kt
  app/src/main/java/com/treasurehunt/ui/profile/FriendViewModel.kt
  app/src/main/java/com/treasurehunt/ui/profile/ProfileFragment.kt
  app/src/main/java/com/treasurehunt/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/treasurehunt/ui/savelog/SaveLogFragment.kt
  app/src/main/java/com/treasurehunt/util/Functions.kt
  app/src/main/res/drawable/ic_circle_white.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: refactoring

#134 [설정화면] 로그아웃, 회원탈퇴, 자동로그인 구현
  app/build.gradle.kts
  app/src/main/java/com/treasurehunt/data/UserPreferencesRepository.kt
  app/src/main/java/com/treasurehunt/data/UserPreferencesRepositoryImpl.kt
  app/src/main/java/com/treasurehunt/data/UserRepository.kt
  app/src/main/java/com/treasurehunt/data/UserRepositoryImpl.kt
  app/src/main/java/com/treasurehunt/data/remote/UserRemoteDataSource.kt
  app/src/main/java/com/treasurehunt/data/remote/UserService.kt
  app/src/main/java/com/treasurehunt/di/DataStoreModule.kt
  app/src/main/java/com/treasurehunt/di/RepositoryModule.kt
  app/src/main/java/com/treasurehunt/ui/home/HomeActivity.kt
  app/src/main/java/com/treasurehunt/ui/login/LoginViewModel.kt
  app/src/main/java/com/treasurehunt/ui/login/SplashFragment.kt
  app/src/main/java/com/treasurehunt/ui/profile/ProfileFragment.kt
  app/src/main/java/com/treasurehunt/ui/setting/DeleteAccountFragment.kt
  app/src/main/java/com/treasurehunt/ui/setting/SettingFragment.kt
  app/src/main/java/com/treasurehunt/ui/setting/SettingViewModel.kt
  app/src/main/res/drawable/background_white_radius.xml
  app/src/main/res/drawable/button_blue_radius.xml
  app/src/main/res/drawable/ic_left_arrow.xml
  app/src/main/res/drawable/ic_logout.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/drawable/ic_user_delete.xml
  app/src/main/res/drawable/ic_warning.xml
  app/src/main/res/layout/fragment_delete_user.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#139 [스플래시/로그인 화면] PreloadFragment에서 프로필 이미지 preload시, Glide에 전달하는 storageRef 변경해 Glide load fail 오류 해결
  app/src/main/java/com/treasurehunt/ui/login/LoginViewModel.kt
  app/src/main/java/com/treasurehunt/ui/login/PreloadFragment.kt
  app/src/main/java/com/treasurehunt/ui/profile/ProfileFragment.kt
Labels: fix

#138 [지도 장소 검색 화면] 홈 지도 화면 상단에 검색바 추가 및 검색 화면 UI 구현, 위치 오버레이 아이콘에 프로필 이미지 적용
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/treasurehunt/data/MapPlaceSearchRepository.kt
  app/src/main/java/com/treasurehunt/data/MapPlaceSearchRepositoryImpl.kt
  app/src/main/java/com/treasurehunt/data/remote/MapPlaceSearchService.kt
  app/src/main/java/com/treasurehunt/data/remote/model/MapPlaceDTO.kt
  app/src/main/java/com/treasurehunt/di/MapPlaceSearchModule.kt
  app/src/main/java/com/treasurehunt/di/NetworkModule.kt
  app/src/main/java/com/treasurehunt/di/RepositoryModule.kt
  app/src/main/java/com/treasurehunt/ui/home/HomeFragment.kt
  app/src/main/java/com/treasurehunt/ui/home/HomeViewModel.kt
  app/src/main/java/com/treasurehunt/ui/model/MapPlaceModel.kt
  app/src/main/java/com/treasurehunt/ui/model/SearchMapPlaceUiState.kt
  app/src/main/java/com/treasurehunt/ui/searchmapplace/MapPlaceClickListener.kt
  app/src/main/java/com/treasurehunt/ui/searchmapplace/SearchMapPlaceFragment.kt
  app/src/main/java/com/treasurehunt/ui/searchmapplace/SearchMapPlaceViewModel.kt
  app/src/main/java/com/treasurehunt/ui/searchmapplace/adapter/SearchMapPlaceAdapter.kt
  app/src/main/java/com/treasurehunt/util/Constants.kt
  app/src/main/java/com/treasurehunt/util/Extensions.kt
  app/src/main/java/com/treasurehunt/util/Functions.kt
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_manage_search.xml
  app/src/main/res/drawable/ic_pin.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search_map_place.xml
  app/src/main/res/layout/item_search_map_place.xml
  app/src/main/res/layout/view_info_window_selected_search_result.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#140 프로필 화면 버그 발견 후 수정 및 홈 화면 버그 수정
  app/src/main/java/com/treasurehunt/ui/home/HomeViewModel.kt
  app/src/main/java/com/treasurehunt/ui/profile/ProfileFragment.kt
Labels: fix

#141 [홈 지도 화면 -> 기록 상세 화면] 수정 중인 기록의 보물상자 마커를 클릭해 상세 화면 진입시 오류 해결
  app/src/main/java/com/treasurehunt/ui/detail/LogDetailFragment.kt
  app/src/main/java/com/treasurehunt/ui/detail/LogDetailViewModel.kt
  app/src/main/res/layout/fragment_logdetail.xml
Labels: fix

#143 [기록 상세 화면] 수정/삭제 기능을 피드 화면에서 진입한 경우도 구분해서 적용
  app/src/main/java/com/treasurehunt/data/local/model/LogEntity.kt
  app/src/main/java/com/treasurehunt/ui/detail/LogDetailFragment.kt
  app/src/main/java/com/treasurehunt/ui/detail/LogDetailViewModel.kt
  app/src/main/java/com/treasurehunt/ui/detail/LogResult.kt
  app/src/main/java/com/treasurehunt/ui/feed/FeedViewModel.kt
  app/src/main/java/com/treasurehunt/ui/model/LogModel.kt
  app/src/main/java/com/treasurehunt/ui/savelog/DatabaseUpdateWorker.kt
  app/src/main/java/com/treasurehunt/ui/savelog/SaveLogFragment.kt
  app/src/main/res/layout/fragment_logdetail.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature
