Repository Sesac-team-03/TreasureHunt, pull requests merged in 2024-02, with the labels that each got.

#80 [홈 지도 화면 및 기록 저장 화면] 지도상에 장소와 마커 클릭 기능 구현 및 기록 저장 확인 버튼 클릭시 로컬과 원격 DB에 연동
  app/build.gradle.kts
  app/src/main/java/com/treasurehunt/data/LogRepository.kt
  app/src/main/java/com/treasurehunt/data/LogRepositoryImpl.kt
  app/src/main/java/com/treasurehunt/data/PlaceRepository.kt
  app/src/main/java/com/treasurehunt/data/PlaceRepositoryImpl.kt
  app/src/main/java/com/treasurehunt/data/UserRepository.kt
  app/src/main/java/com/treasurehunt/data/local/PlaceDao.kt
  app/src/main/java/com/treasurehunt/data/local/model/LogEntity.kt
  app/src/main/java/com/treasurehunt/data/local/model/PlaceEntity.kt
  app/src/main/java/com/treasurehunt/data/remote/LogService.kt
  app/src/main/java/com/treasurehunt/data/remote/PlaceService.kt
  app/src/main/java/com/treasurehunt/data/remote/UserService.kt
  app/src/main/java/com/treasurehunt/data/remote/model/MapUiState.kt
  app/src/main/java/com/treasurehunt/data/remote/model/PlaceDTO.kt
  app/src/main/java/com/treasurehunt/data/remote/model/PlaceRemoteDataSource.kt
  app/src/main/java/com/treasurehunt/data/remote/model/RemoteIdWrapper.kt
  app/src/main/java/com/treasurehunt/data/remote/model/UserRemoteDataSource.kt
  app/src/main/java/com/treasurehunt/ui/detail/DetailFragment.kt
  app/src/main/java/com/treasurehunt/ui/home/HomeFragment.kt
  app/src/main/java/com/treasurehunt/ui/home/HomeViewModel.kt
  app/src/main/java/com/treasurehunt/ui/home/MapDialogFragment.kt
  app/src/main/java/com/treasurehunt/ui/login/LoginViewModel.kt
  app/src/main/java/com/treasurehunt/ui/login/SplashFragment.kt
  app/src/main/java/com/treasurehunt/ui/model/LogModel.kt
  app/src/main/java/com/treasurehunt/ui/model/MapSymbol.kt
  app/src/main/java/com/treasurehunt/ui/model/MapUiState.kt
  app/src/main/java/com/treasurehunt/ui/model/PlaceModel.kt
  app/src/main/java/com/treasurehunt/ui/savelog/SaveLogFragment.kt
  app/src/main/java/com/treasurehunt/ui/savelog/SaveLogViewModel.kt
  app/src/main/java/com/treasurehunt/util/ConnectivityRepository.kt
  app/src/main/java/com/treasurehunt/util/Functions.kt
  app/src/main/res/layout/fragment_map_dialog.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: feature

#83 공유기능 추가 및 스플래시 무한반복 수정
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/treasurehunt/ui/detail/ImageItem.kt
  app/src/main/java/com/treasurehunt/ui/detail/ImageSliderAdapter.kt
  app/src/main/java/com/treasurehunt/ui/detail/LogDetailFragment.kt
  app/src/main/java/com/treasurehunt/ui/login/SplashFragment.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: fix

#88 refactor: 로그인 화면 로직 수정, 에러 스낵바 추가, 기타 리팩토링
  app/src/main/java/com/treasurehunt/ui/login/LogInFragment.kt
  app/src/main/java/com/treasurehunt/ui/login/LoginViewModel.kt
  app/src/main/java/com/treasurehunt/ui/login/SplashFragment.kt
  app/src/main/res/values/strings.xml
Labels: refactoring

#91 [프로필 화면 - 친구 탭 페이지] 친구 화면에서 친구 검색, 친구 추가, 현재 친구목록 표시, 친구 삭제 기능 구현
  app/src/main/java/com/treasurehunt/data/UserRepository.kt
  app/src/main/java/com/treasurehunt/data/UserRepositoryImpl.kt
  app/src/main/java/com/treasurehunt/data/remote/UserRemoteDataSource.kt
  app/src/main/java/com/treasurehunt/data/remote/UserService.kt
  app/src/main/java/com/treasurehunt/data/remote/model/UserDTO.kt
  app/src/main/java/com/treasurehunt/di/LocalModule.kt
  app/src/main/java/com/treasurehunt/di/NetworkModule.kt
  app/src/main/java/com/treasurehunt/di/RepositoryModule.kt
  app/src/main/java/com/treasurehunt/ui/home/HomeViewModel.kt
  app/src/main/java/com/treasurehunt/ui/model/FriendUiState.kt
  app/src/main/java/com/treasurehunt/ui/model/UserModel.kt
  app/src/main/java/com/treasurehunt/ui/profile/FriendAdapter.kt
  app/src/main/java/com/treasurehunt/ui/profile/FriendClickListener.kt
  app/src/main/java/com/treasurehunt/ui/profile/FriendFragment.kt
  app/src/main/java/com/treasurehunt/ui/profile/FriendViewModel.kt
  app/src/main/java/com/treasurehunt/ui/profile/ProfileFragment.kt
  app/src/main/java/com/treasurehunt/ui/profile/ProfileViewPagerAdapter.kt
  app/src/main/java/com/treasurehunt/ui/profile/SearchFriendAdapter.kt
  app/src/main/java/com/treasurehunt/util/Extensions.kt
  app/src/main/res/drawable/ic_add_friend.xml
  app/src/main/res/drawable/ic_dissatisfied.xml
  app/src/main/res/drawable/ic_remove_friend.xml
  app/src/main/res/drawable/ic_search_friend.xml
  app/src/main/res/layout/fragment_friend.xml
  app/src/main/res/layout/item_friend.xml
  app/src/main/res/layout/item_search_friend.xml
  app/src/main/res/values/strings.xml
Labels: feature

#94 [피드 화면]
  app/src/main/java/com/treasurehunt/data/ImageRepository.kt
  app/src/main/java/com/treasurehunt/data/ImageRepositoryImpl.kt
  app/src/main/java/com/treasurehunt/data/local/model/LogEntity.kt
  app/src/main/java/com/treasurehunt/data/remote/ImageRemoteDataSource.kt
  app/src/main/java/com/treasurehunt/data/remote/ImageService.kt
  app/src/main/java/com/treasurehunt/data/remote/model/ImageDTO.kt
  app/src/main/java/com/treasurehunt/data/remote/model/LogDTO.kt
  app/src/main/java/com/treasurehunt/ui/BindingAdapters.kt
  app/src/main/java/com/treasurehunt/ui/feed/FeedFragment.kt
  app/src/main/java/com/treasurehunt/ui/feed/FeedViewModel.kt
  app/src/main/java/com/treasurehunt/ui/feed/LogClickListener.kt
  app/src/main/java/com/treasurehunt/ui/feed/adapter/FeedAdapter.kt
  app/src/main/java/com/treasurehunt/ui/home/HomeFragment.kt
  app/src/main/java/com/treasurehunt/ui/model/FeedUiState.kt
  app/src/main/java/com/treasurehunt/ui/model/LogModel.kt
  app/src/main/java/com/treasurehunt/ui/savelog/ImageModel.kt
  app/src/main/java/com/treasurehunt/ui/savelog/SaveLogFragment.kt
  app/src/main/java/com/treasurehunt/util/ConnectivityRepository.kt
  app/src/main/res/drawable/ic_images_icon.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#100 refactor: 가본 장소 관련 이름 변경 place -> visit
  app/src/main/java/com/treasurehunt/ui/home/HomeFragment.kt
  app/src/main/java/com/treasurehunt/ui/home/HomeViewModel.kt
  app/src/main/java/com/treasurehunt/ui/home/MapDialogFragment.kt
  app/src/main/res/layout/fragment_map_dialog.xml
  app/src/main/res/values/strings.xml
Labels: refactoring

#102 기록 저장 화면에서 등록 버튼 클릭 후, CloudStorage 이미지 업로드 -> 파이어베이스 DB 업데이트를 백그라운드에서 순차 처리 및 프로그레스바 알림 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/treasurehunt/CustomWorkerFactory.kt
  app/src/main/java/com/treasurehunt/TreasureHuntApplication.kt
  app/src/main/java/com/treasurehunt/data/remote/model/ImageDTO.kt
  app/src/main/java/com/treasurehunt/ui/home/HomeActivity.kt
  app/src/main/java/com/treasurehunt/ui/model/ImageModel.kt
  app/src/main/java/com/treasurehunt/ui/savelog/DatabaseUpdateWorker.kt
  app/src/main/java/com/treasurehunt/ui/savelog/ImageClickListener.kt
  app/src/main/java/com/treasurehunt/ui/savelog/ImageModel.kt
  app/src/main/java/com/treasurehunt/ui/savelog/ImageUploadWorker.kt
  app/src/main/java/com/treasurehunt/ui/savelog/SaveLogFragment.kt
  app/src/main/java/com/treasurehunt/ui/savelog/SaveLogViewModel.kt
  app/src/main/java/com/treasurehunt/ui/savelog/adapter/SaveLogAdapter.kt
  app/src/main/java/com/treasurehunt/util/Constants.kt
  app/src/main/res/layout/item_savelog.xml
  app/src/main/res/values/strings.xml
Labels: feature
